name: bio-agent
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - salmon=1.10.3
  - python
  - pip
  - pip:
      - 'git+https://github.com/huggingface/smolagents.git@main#egg=smolagents[litellm]'
      - openai
